name: Deploy React Vite to GitHub Pages

on:
  # Akan tertrigger setiap kali ada push ke branch 'main'
  push:
    branches: ["main"]
  # Memungkinkan Anda menjalankan workflow ini secara manual dari tab Actions
  workflow_dispatch:

# Menetapkan permission untuk GITHUB_TOKEN agar bisa mendeploy ke Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Mencegah deployment yang tumpang tindih
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # Gunakan versi Node.js yang sesuai dengan project Anda
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Direktori output default dari Vite adalah 'dist'
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
